### ISSUE TITLE
Support for RTL8188fu on Solus

### ISSUE THREAD

**Issue by KeivnL** [Alexander88207/Tomomi#23]
Sources if it helps:
https://github.com/ulli-kroll/rtl8188fu
https://github.com/kelebek333/rtl8188fu

**Comment by Alexander88207** [comment]
Hello @KeivnL,

Can you try out the newest git version?

**Comment by KeivnL** [comment]
The git part was ok, but then got this:
Building driver
make ARCH=x86_64 CROSS_COMPILE= -C /lib/modules/5.2.7-123.current/build M=/home/keivn/RTL-Driver-Installer-Files/rtl8188fu  modules
make[1]: Entering directory '/usr/src/linux-headers-5.2.7-123.current'
  CC [M]  /home/keivn/RTL-Driver-Installer-Files/rtl8188fu/core/rtw_cmd.o
/usr/lib64/gcc/x86_64-solus-linux/8/cc1: error while loading shared libraries: libisl.so.19: cannot open shared object file: No such file or directory
make[2]: *** [scripts/Makefile.build:279: /home/keivn/RTL-Driver-Installer-Files/rtl8188fu/core/rtw_cmd.o] Error 1
make[1]: *** [Makefile:1597: _module_/home/keivn/RTL-Driver-Installer-Files/rtl8188fu] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.2.7-123.current'
make: *** [Makefile:435: modules] Error 2
 Installing driver 
install -p -m 644 .ko  /lib/modules/5.2.7-123.current/kernel/drivers/net/wireless/
install: não foi possível obter estado de '.ko': Arquivo ou diretório inexistente
make: *** [Makefile:445: install] Error 1
Cleanup & make the driver ready for an reinstallation
rm: remover arquivo comum 'rtl8188fu/.git/objects/pack/pack-f0e72d82938f8a420a110117e2fe555dabe8a9ff.pack' protegido contra escrita? 

I've tried to compile manually some time before trying the installer and was getting the same error. Maybe the driver source need some code changes, but I know almost nothing about this hacky thing

**Comment by Alexander88207** [comment]
Can you install gcc?

**Comment by Alexander88207** [comment]
I closing now the issue for no replay in 30 day.
