### ISSUE TITLE
Make a menu for selecting kernel version 

### ISSUE THREAD

**Issue by cata0309** [Alexander88207/Tomomi#24]
Hello ! I helped on the Solus Rtl8723de driver in the past and I want to contribute more.
I noticed that having the most recent kernel( current ) has a lot of downsides like crashes or reboot/ shutdown freeze. I installed lts but the option from the installer is still selecting the 5 and above branch from the rtl8723de repository.
What I did to solve this ?
I modified the script so I clone the specific branch for the kernel I have( lts on Solus is 4.9) 
I replaced :
``git clone https://github.com/smlinux/rtl8723de.git``
with
``git clone --single-branch --branch 4.10-down https://github.com/smlinux/rtl8723de.git``
and the installation went smooth without any errors.

Feature request:
Remove the dialog with the Current and Lts kernel selection as it is not working and put a new select screen with option available in the repos like:
1. 5.0 and up
2. 4.10 and up
3. 4.9 and down
something like that will help choosing the kernel much more effective.
I will prepare a pull request in the future if the idea is not seen as a good idea.

**Comment by Alexander88207** [comment]
Hello @cata0309,

i accept your idea.

**Comment by cata0309** [comment]
I know that, but trying to install on curremt kernel with lts headers it's definetely not a good idea

**Comment by Alexander88207** [comment]
if current gets select then current headers gets installed.

**Comment by Alexander88207** [comment]
I also think about to write the script to a full zenity gui. This will then look like this 
![image](https://user-images.githubusercontent.com/37543796/64721978-d8ab4d00-d4cd-11e9-8c4d-7f89cde95c65.png)

**Comment by cata0309** [comment]
It wouldn't be a bad idea at all.

**Comment by Alexander88207** [comment]
Alright 😉

**Comment by Alexander88207** [comment]
ehm, do you use any instant messenger?

i dont wont use github as a messenger.

**Comment by cata0309** [comment]
Of course, facebook messenger, whatsapp, signal, discord, reddit

**Comment by Alexander88207** [comment]
oh nice! then here :) https://discordapp.com/invite/Mm3aNuQ

**Comment by Alexander88207** [comment]
Done :)
