### ISSUE TITLE
Please add RTL8812BU to your script (TP-LINK Archer T3U AC1300 USB WLAN Stick)

### ISSUE THREAD

**Issue by Coonaps** [Alexander88207/Tomomi#25]

**Comment by Alexander88207** [comment]
Thank you for your submission. I'll start tomorrow to add the RTL8812bu.

**Comment by Coonaps** [comment]
> Thank you for your submission. I'll start tomorrow to add the RTL8812bu.

Wow thanks, that was a quick reply!

**Comment by Alexander88207** [comment]
Hello,

Can you test it please with the latest commit?

**Comment by Coonaps** [comment]
You are a god damn genius man. Thank you sooo much, wish I could program like that! Great work!

![Screenshot from 2019-09-30 21:03:43](https://user-images.githubusercontent.com/55458327/65908045-de59cb80-e3c5-11e9-8bf4-12c6a36f1068.png)

**Comment by Alexander88207** [comment]
So your desired device works now? :)

**Comment by Coonaps** [comment]
Working perfectly as I type :-)

**Comment by Alexander88207** [comment]
All right, then have fun and have a nice evening from my time zone. :smiley:
