### ISSUE TITLE
Unable to install - see screenshot for errors

### ISSUE THREAD

**Issue by Coonaps** [Alexander88207/Tomomi#26]
**Describe the bug**
See screenshot for detailed description.
![Screenshot from 2019-11-21 08:52:15](https://user-images.githubusercontent.com/55458327/69318134-d0ddf680-0c3c-11ea-9a1d-5058c3790e03.png)

**To Reproduce**
Happens every time I run the script

**Expected behavior**
Complete installation, working WiFi

**Screenshots**
check

**Desktop (please complete the following information):**
 - OS: Solus on current kernel

**Comment by Alexander88207** [comment]
![image](https://user-images.githubusercontent.com/37543796/69319555-b0636b80-0c3f-11ea-9aff-bae08c5de23e.png)

Can you try to restart your computer?

**Comment by Coonaps** [comment]
Same error after reboot 
![Screenshot from 2019-11-21 09:58:29](https://user-images.githubusercontent.com/55458327/69322639-87de7000-0c45-11ea-8242-2dddc0dd4fee.png)

**Comment by Alexander88207** [comment]
What is the output of `sudo eopkg it git make` ?

**Comment by Coonaps** [comment]
Install?
![Screenshot from 2019-11-21 10:03:05](https://user-images.githubusercontent.com/55458327/69322980-2074f000-0c46-11ea-813b-665e5ff85460.png)

**Comment by Alexander88207** [comment]
Yes

**Comment by Coonaps** [comment]
Thanks, working like a charm!
![Screenshot from 2019-11-21 10:06:04](https://user-images.githubusercontent.com/55458327/69323212-8feadf80-0c46-11ea-9f88-d3f631a45d97.png)
