### ISSUE TITLE
Errors on newer linux kernel building rtl8723de

### ISSUE THREAD

**Issue by premraj59** [Alexander88207/Tomomi#29]
**Describe the bug**
I had no problems with installation till linux kernel 5.6.6 I recently updated to 5.6.15 and the install fails with errors. I have attached the screenshot.

![DeepinScreenshot_select-area_20200530162257](https://user-images.githubusercontent.com/53263555/83326530-657f7c00-a292-11ea-8af3-e1ecc7a54b7f.png)

I am using arch linux.

**Comment by Alexander88207** [comment]
Hello @premraj59,

can you post the full log please?

**Comment by premraj59** [comment]
![DeepinScreenshot_select-area_20200530192347](https://user-images.githubusercontent.com/53263555/83330393-36760400-a2ac-11ea-8b03-26e837e380d9.png)
![DeepinScreenshot_select-area_20200530192400](https://user-images.githubusercontent.com/53263555/83330395-383fc780-a2ac-11ea-9649-b5fb3ca63a03.png)
![DeepinScreenshot_select-area_20200530192409](https://user-images.githubusercontent.com/53263555/83330397-3a098b00-a2ac-11ea-9729-82e298de7035.png)
![DeepinScreenshot_select-area_20200530192419](https://user-images.githubusercontent.com/53263555/83330398-3c6be500-a2ac-11ea-8f90-11bc9055ce29.png)
![DeepinScreenshot_select-area_20200530192427](https://user-images.githubusercontent.com/53263555/83330400-3d9d1200-a2ac-11ea-9387-41d531708120.png)
![DeepinScreenshot_select-area_20200530192436](https://user-images.githubusercontent.com/53263555/83330401-3f66d580-a2ac-11ea-8d3f-50692b6f5c3a.png)
![DeepinScreenshot_select-area_20200530192447](https://user-images.githubusercontent.com/53263555/83330402-41309900-a2ac-11ea-94f5-472e59eb6a70.png)
![DeepinScreenshot_select-area_20200530192501](https://user-images.githubusercontent.com/53263555/83330404-4261c600-a2ac-11ea-8a90-b4357dd4d67c.png)
![DeepinScreenshot_select-area_20200530192513](https://user-images.githubusercontent.com/53263555/83330406-4392f300-a2ac-11ea-9924-a44331ebf1ab.png)
![DeepinScreenshot_select-area_20200530192522](https://user-images.githubusercontent.com/53263555/83330407-44c42000-a2ac-11ea-872f-405b9728bb78.png)

**Comment by Alexander88207** [comment]
@premraj59 I have now added the current branch of your driver, can you test it?

I also apologize for the long wait should this have been important.

**Comment by premraj59** [comment]
![DeepinScreenshot_select-area_20200531180447](https://user-images.githubusercontent.com/53263555/83352488-5ae3e600-a369-11ea-8a85-b6eeed670d3a.png)

Sorry for late response.

**Comment by premraj59** [comment]
It still don't work.

**Comment by Alexander88207** [comment]
Hmm, this seems to be a problem on your side, is the package linux-headers up to date with your kernel version?

**Comment by premraj59** [comment]
Yes. It is a make error. I managed to get a fixed driver from smlinux after posting the same issue there.

https://github.com/smlinux/rtl8723de/issues/69

**Comment by Alexander88207** [comment]
Nice!
